[config]
schemaVersion = "0.0.1"


[package]
namespace = "Kuipo"
name = "NSFW Resprite"
versionNumber = "1.0.0"
description = "Replaces most of the 2D artwork in the game with NSFW images"
websiteUrl = "https://github.com/Kuipo/Hades2-NSFW-Resprite"
containsNsfwContent = true

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.60"
SGG_Modding-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[[build.copy]]
source = "./packages"
target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
